version: '3.9'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
  adminer:
    image: adminer
    restart: always
    ports:
      - 6380:8080
